class Slug:
    role_core_sw = "core_sw"
    role_edge_sw = "edge_sw"

    site_group_ookayama_north = "ookayama-n"
    site_group_ookayama_south = "ookayama-s"
    site_group_ookayama_east = "ookayama-e"
    site_group_ookayama_west = "ookayama-w"
    site_group_ishikawadai = "ishikawadai"
    site_group_midorigaoka = "midorigaoka"
    site_group_tamachi = "tamachi"

    tag_mgmt_vlan_border_ookayama = "mgmt-vlan-bo"
    tag_mgmt_vlan_border_suzukake = "mgmt-vlan-bs"
    tag_mgmt_vlan_core_ookayama = "mgmt-vlan-co"
    tag_mgmt_vlan_core_suzukake = "mgmt-vlan-cs"
    tag_mgmt_vlan_edge_ookayama = "mgmt-vlan-eo"
    tag_mgmt_vlan_edge_suzukake = "mgmt-vlan-es"
    tag_wifi_mgmt_vlan_ookayama1 = "wlan-mgmt-vlan-o1"
    tag_wifi_mgmt_vlan_ookayama2 = "wlan-mgmt-vlan-o2"
    tag_wifi_mgmt_vlan_suzukake = "wlan-mgmt-vlan-s"