class Slug:
    class Role:
        CoreSw = "core_sw"
        EdgeSw = "edge_sw"

    class SiteGroup:
        Ishikawadai    = "ishikawadai"
        Midorigaoka    = "midorigaoka"
        OokayamaEast   = "ookayama-e"
        OokayamaNorth  = "ookayama-n"
        OokayamaSouth  = "ookayama-s"
        OokayamaWest   = "ookayama-w"
        Tamachi        = "tamachi"

    class Tag:
        CoreDownstream         = "downlink"
        CoreMaster             = "mclag-master-core"
        CoreOokayamaMaster     = "mclag-master-co"
        CoreOokayamaSlave      = "mclag-slave-co"
        CoreSlave              = "mclag-slave-core"
        CoreSuzukakeMaster     = "mclag-master-cs"
        CoreSuzukakeSlave      = "mclag-slave-cs"
        EdgeUpstream           = "uplink"
        MgmtVlanBorderOokayama = "mgmt-vlan-bo"
        MgmtVlanBorderSuzukake = "mgmt-vlan-bs"
        MgmtVlanCoreOokayama   = "mgmt-vlan-co"
        MgmtVlanCoreSuzukake   = "mgmt-vlan-cs"
        MgmtVlanEdgeOokayama   = "mgmt-vlan-eo"
        MgmtVlanEdgeSuzukake   = "mgmt-vlan-es"
        Rspan                  = "rspan"
        VlanOokayama           = "vlan-o"
        VlanSuzukake           = "vlan-s"
        Wifi                   = "wifi"
        WifiMgmtVlanOokayama1  = "wlan-mgmt-vlan-o1"
        WifiMgmtVlanOokayama2  = "wlan-mgmt-vlan-o2"
        WifiMgmtVlanSuzukake   = "wlan-mgmt-vlan-s"


    ## Deprecated slugs - soon to be removed
    role_core_sw = "core_sw"
    role_edge_sw = "edge_sw"

    site_group_ookayama_north = "ookayama-n"
    site_group_ookayama_south = "ookayama-s"
    site_group_ookayama_east  = "ookayama-e"
    site_group_ookayama_west  = "ookayama-w"
    site_group_ishikawadai    = "ishikawadai"
    site_group_midorigaoka    = "midorigaoka"
    site_group_tamachi        = "tamachi"

    tag_core_downstream           = "downlink"
    tag_edge_upstream             = "uplink"
    tag_core_master               = "mclag-master-core"
    tag_core_slave                = "mclag-slave-core"
    tag_core_ookayama_master      = "mclag-master-co"
    tag_core_ookayama_slave       = "mclag-slave-co"
    tag_core_suzukake_master      = "mclag-master-cs"
    tag_core_suzukake_slave       = "mclag-slave-cs"
    tag_mgmt_vlan_border_ookayama = "mgmt-vlan-bo"
    tag_mgmt_vlan_border_suzukake = "mgmt-vlan-bs"
    tag_mgmt_vlan_core_ookayama   = "mgmt-vlan-co"
    tag_mgmt_vlan_core_suzukake   = "mgmt-vlan-cs"
    tag_mgmt_vlan_edge_ookayama   = "mgmt-vlan-eo"
    tag_mgmt_vlan_edge_suzukake   = "mgmt-vlan-es"
    tag_vlan_ookayama             = "vlan-o"
    tag_vlan_suzukake             = "vlan-s"
    tag_wifi_mgmt_vlan_ookayama1  = "wlan-mgmt-vlan-o1"
    tag_wifi_mgmt_vlan_ookayama2  = "wlan-mgmt-vlan-o2"
    tag_wifi_mgmt_vlan_suzukake   = "wlan-mgmt-vlan-s"
    tag_wifi                      = "wifi"
    tag_rspan                     = "rspan"

