FROM ubuntu:22.04

ENV PATH="$HOME/.local/bin:$PATH"

RUN apt-get update \
 && apt-get upgrade -y \
 && DEBIAN_FRONTEND=noninteractive \
    apt-get install -y --no-install-recommends \
      python3 \
      python3-pip \
 && apt-get clean \
 && rm -rf /var/lib/apt/*

RUN python3 -m pip install --upgrade ansible
